import Head from "next/head";
import React from "react";
import Landing from "../src/components/landing";
import Navbar from "../src/components/navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Landing />
    </div>
  );
}
